name: first-github-action
run-name: ${{ github.actor }} first action
on: [push]
jobs:
  test-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World"
